feat: allow for email/password login
AtB-AS/webshop pull request #227
Opened 2021-06-03 12:03 UTC by mikaelbr

Fixes #51

2021-06-11 10:18 UTC, tormoseng commented
Noen kommentarer:

1. Hva skjer tilstandsmessig når man bekrefter epost - kommer rett inn i onboardingen i nytt vindu, for så å bli forvirret, gå tilbake til side og trykke “det er gjort” - og da havne inn i onboarding igjen. Potensielt to åpne vinduer med onboarding.
--> Aha. Fulgte et parallelt løp med to onboardinger, og da ble endelig Navn tatt fra den onboardingstab som utfylt sist.

2. Trykker på verifikasjonsepost og kommer inn i onboarding. Fullfører. Alt ok. Går deretter til den andre tab-en og trykker “Det er gjort”. Havner da inn i nettbutikken, men alle topp-lenker er da borte. Kommer frem førts ved en refresh.

3. Min konto (uten å ha lagret tlf.nr): Legg til tlf.nr: Legger til 8 siffer (inkl. gyldig tlf.nr) og får da beskjed om at “Telefonnummeret må bestå av 8 siffer”.

4. Min konto (har lagret tlf.nr): Nummeret fremkommer med “+47", så prøver å endre til noe annet inkl. “+47", men får da feilmld”. Telefonnummeret må bestå av 8 siffer”.

2021-06-11 10:24 UTC, mikaelbr commented
> Hva skjer tilstandsmessig når man bekrefter epost - kommer rett inn i onboardingen i nytt vindu, for så å bli forvirret, gå tilbake til side og trykke “det er gjort” - og da havne inn i onboarding igjen. Potensielt to åpne vinduer med onboarding.

Dette er dessverre typisk slik det blir med verifikasjonsepost og er ganske vanlig. Det er ingen måte å "finne den originale" fanen på når du går tilbake. Det er mulig vi kunne ha lyttet på profiloppdatering i sanntid for å indikere andre oppslag, men jeg tror det fort blir mer komplekst enn nytteverdien akkurat her.

2021-06-11 10:25 UTC, mikaelbr commented
Akkurat nå er vi låst til +47 nummer fra Entur tror jeg. Så jeg tror faktisk vi må ta en runde for å tvinge det i grensesnitt og i kode.

2021-06-11 10:37 UTC, mikaelbr commented
Skal ha fikset det du påpeker nå, @tormoseng . Sjekk gjerne når det blir rullet ut!

2021-06-14 11:05 UTC, tormoseng approved these changes
Dette ser bra ut gjennom testing.

@mikaelbr En liten kommentar. Ved opplesing med VoiceOver så leser den på innloggingssiden "Logg inn på din AtB-profil med e-post og passord eller" deretter må man flytte fokus for å få med "bruk engangskode fra telefonen". Flytt deretter fokus videre for å få lest opp "punktum"

2021-06-14 11:10 UTC, mjenssen requested changes

2021-06-14 11:10 UTC, mjenssen commented on src/static/index.js
> +                    'Det er alt registrert en konto på denne eposten. Prøv å logg inn.'
"epostadresse" vel? En epost er ei melding du får sendt til en adresse.

2021-06-14 11:10 UTC, mjenssen commented on src/static/index.js
> +        message: 'Du er blitt logget ut.'
Burde ikke dette være "du har logget ut" eller "du er utlogget", evt "du er nå utlogget"?

2021-06-15 06:03 UTC, mikaelbr commented on src/static/index.js
> +        message: 'Du er blitt logget ut.'
Dette kan også skje uvillig. Derfor jeg var litt usikker på hvordan vi best kan formulere det. Det kan både forekomme ved utlogging eller tvangsutlogging. `Du er utlogget` holder vel

2021-06-15 06:19 UTC, mikaelbr commented
> @mikaelbr En liten kommentar. Ved opplesing med VoiceOver så leser den på innloggingssiden "Logg inn på din AtB-profil med e-post og passord eller" deretter må man flytte fokus for å få med "bruk engangskode fra telefonen". Flytt deretter fokus videre for å få lest opp "punktum"

Hm. Dette må nesten være standardoppførsel, eller? Det er ingenting spesielt såvidt jeg kan se med lenken som en del av tekst her.

2021-06-16 06:37 UTC, tormoseng commented
> Sjekk ny deploya ting på #227 nå. Både at det blir rett i screen readers og med validator.

Validator bak #227 gikk fint nå. Eneste jeg er usikker på er hvordan de som *faktisk* benytter skjermleser vil "se" beskjeden nå. Med VoiceOver må fokus flyttes til etter "Logg inn ..." (fokus på tomt felt) for å få lest opp "Brukere av skjermleser ...". (se fokus på skjermbildet under)

![image](https://user-images.githubusercontent.com/5812433/122169681-f87b5c00-ce7d-11eb-9f4c-91f942c13b2e.png)

2021-06-16 06:55 UTC, mikaelbr commented
Det blir brukt en ganske vanlig teknikk for å kun vise meldinger til skjermlesere så lurer på om de ikke er så ukjent med konseptet. Men det kan være fint å teste en gang i en brukertest tenker jeg!

2021-06-16 07:07 UTC, mjenssen approved these changes

2021-06-16 07:08 UTC, merged