feat: adds security headers to firebase
AtB-AS/webshop pull request #271
Opened 2021-06-28 07:34 UTC by mikaelbr

2021-06-28 10:59 UTC, mjenssen requested changes

2021-06-28 10:59 UTC, mjenssen commented on firebase.json
> +                        "value": "default-src 'self';font-src fonts.gstatic.com;style-src 'unsafe-inline' 'self' fonts.googleapis.com;connect-src https://*.googleapis.com https://api.staging.mittatb.
`dev.mittatb.no` burde ikke brukes lengre - mente du egentlig `prod.mittatb.no` her, siden det ikke er nevnt?

2021-06-29 07:01 UTC, mikaelbr commented on firebase.json
> +                        "value": "default-src 'self';font-src fonts.gstatic.com;style-src 'unsafe-inline' 'self' fonts.googleapis.com;connect-src https://*.googleapis.com https://api.staging.mittatb.
🤦  yes

2021-06-29 07:15 UTC, mjenssen approved these changes

2021-06-29 07:19 UTC, mikaelbr commented
Par ekstra ting jeg oppdaget. Kunne egentlig ha tenkt meg å bruke strict CSP og nonce men finner ingen umiddelbar enkel måte å løse det på med Firebase Hosting. Kanskje via metatags injected i byggetid men.. bruker ikke mer tid på det nå

2021-06-29 07:32 UTC, merged

2021-06-29 07:43 UTC, tormoseng commented
![Screenshot 2021-06-29 at 09 43 22](https://user-images.githubusercontent.com/5812433/123757670-81eb4f00-d8be-11eb-9bea-f889913339d3.png)

2021-06-29 10:32 UTC, tormoseng commented
Testet OK i staging