feat: Forbedrer UU for skjema og inputs
AtB-AS/webshop pull request #298
Opened 2021-07-06 10:41 UTC by mikaelbr

- Legger til indikasjon på ventende innhold.
- Legger til bedre rolle for feilmeldinger som leses opp ved input.

2021-07-06 12:56 UTC, tormoseng requested changes
a11y-testene fant dette på PR-url (kanskje litt rart de ikke fant det før endringene?)
<img width="1688" alt="Screenshot 2021-07-06 at 14 53 02" src="https://user-images.githubusercontent.com/5812433/124603586-5e01ad80-de6a-11eb-8179-4bd865db048c.png">

Kan teste manuelt med VO og TB etterpå.

2021-07-06 13:05 UTC, mikaelbr commented
Ser ut som en feil jeg innfører ja. Ikke klar over at progress måtte ha label. Trodde det holdt med valuetext. Jeg skal fikse opp

2021-07-06 13:54 UTC, tormoseng commented
@mikaelbr 
- a11y-testene gikk nå fint gjennom.
- Ellers kommer det feilmelding opp for både VO og TB på passordfeil, mens det er forskjeller hvordan VO og TB håndterer andre ting:
  - feil t:kort-nummer blir lest opp på TB, men ikke VO
  - for få tegn i telefonnummer blir lest opp på TB, men ikke VO
  - lagre ved trykk på lagre-knapper i min profil blir lest opp som "laster" på VO, men ingen beskjed på TB.
  - Endring av input-feltet soner i billettbestilling gir en liten vibrasjon - det er vel det som tolkes som "lastet"?

2021-07-07 07:10 UTC, mikaelbr commented
Ja, forskjellige lesere behandler ting litt forskjellig. Jeg har lagt på noe ekstra greier for å forbedre litt mer

2021-07-07 07:51 UTC, tormoseng commented
Får fortsatt ikke lest opp feilmld på VO vedrørende feil t:kort og for få tegn i tlf.nr. Men mulig feilmeldinger på VO kunne vært egen sak?

2021-07-07 08:00 UTC, mikaelbr commented
I onboarding eller Account? Jeg tror det er en greie med VO at den avbryter opplesingen for å lese opp innholdet i tekstfeltet man er i. Men jeg skal debugge litt

2021-07-07 08:06 UTC, tormoseng commented
> I onboarding eller Account? Jeg tror det er en greie med VO at den avbryter opplesingen for å lese opp innholdet i tekstfeltet man er i. Men jeg skal debugge litt

I minprofil

2021-07-07 10:30 UTC, mikaelbr commented
Jeg får opp feilmelding i VoiceOver jeg altså 🤔

2021-07-07 11:08 UTC, tormoseng commented
> Jeg får opp feilmelding i VoiceOver jeg altså 🤔

Jammen, i Safari går det fint, men ikke Chrome som jeg testet på. OK, la den gå :-)

2021-07-07 13:02 UTC, merged