Prepare limited carnet rollout
AtB-AS/webshop pull request #345
Opened 2021-08-13 21:37 UTC by mjenssen

Closes #343

2021-08-16 08:25 UTC, gorandalum requested changes
Ser bra ut! Hadde en kommentar om styling av disabled som kan ses på før dette merges.

2021-08-16 11:05 UTC, tormoseng approved these changes
Ser greit ut for meg!

2021-08-16 13:23 UTC, mjenssen commented on src/static/styles/ui.scss
> +    opacity: 0.2;
Jeg gikk for 0.2 siden dette var brukt andre steder, f.eks. på knapper:

```
.ui-button--disabled > * {
    opacity: 0.2;
}
```

`opacity` påvirker mer enn bare tekstfargen, så er ikke så sikker på om det du foreslår er bra nok. Ingen opacity i themet heller, så det må evt. fikses først.

2021-08-17 07:40 UTC, gorandalum commented on src/static/styles/ui.scss
> +    opacity: 0.2;
Jeg har enig i at opacity og tekstfarge burde vært mer frikoblet i designsystemet. Men i appen har vi ikke støtt på så mange prøblemer med å bruke `text-colors-disabled` på `color`-egenskapen, som da inneholder en opacity. Men hvis opacity er satt direkte flere steder i webshop så er det nok ikke så viktig å gjøre om på det for akkurat denne saken.

Uansett bør man ha en avklaring på riktig opacity slik at skissene og implementasjonen er i synk.

2021-08-17 12:29 UTC, gorandalum commented on src/static/styles/ui.scss
> +    opacity: 0.2;
Endret til 0.2 i skissene av Magnus.

2021-08-17 12:29 UTC, gorandalum approved these changes

2021-08-17 17:37 UTC, merged