feat: Change payment button to link
AtB-AS/webshop pull request #460
Opened 2021-12-21 15:13 UTC by gorandalum

2021-12-22 12:33 UTC, rosvik approved these changes

2022-01-03 11:36 UTC, mikaelbr requested changes

2022-01-03 11:36 UTC, mikaelbr commented on src/elm/Page/Shop/Summary.elm
> +                |> B.setElement H.a
Hm. er ikke så sikker på at dette skal være en lenke jeg. Lenker skal ha href og gjerne ha da semantikken rundt å kunne kopiere URL som følge av det (eller åpne i nytt vindu osv). Dette er en action som fører på et punkt til en ny visning. Men semantisk sett mener jeg det er en button.

2022-01-03 11:41 UTC, mikaelbr commented
Jeg noe strengt rejected denne PR-en jeg. Men min oppfatning er egentlig at det er label eller title som trengs for å oppfylle behovet som beskrevet i #183.

2022-01-03 13:07 UTC, gorandalum commented
Den er god, du har overbevist meg 👍  Jeg tok bort endringen til `<a>` nå, og lar `aria-label` være igjen.

2022-01-03 13:09 UTC, mikaelbr approved these changes
Det var jo enkelt. Slapp jo til og med å kjøre igjennom XHTML 1.0 Strict Validator (det hadde heller ikke vært gyldig i nåværende specc altså, men morsommere med XHTML)

2022-01-03 14:07 UTC, merged