feat: Redesigns login and making it more robust
AtB-AS/webshop pull request #80
Opened 2021-04-28 08:33 UTC by mikaelbr

Closes #72

- Oppdaterer designet til prototype/tentativ v0.2 for litt mer innbydende login.
- Gjør innlogging mer robust for feilhåndtering og visning av feil.
- Fikser feil med unødvendig mye datauthenting for brukerinformasjon.
- Fikser feil med hengende innlogging noen ganger. Mulig dette kan forekomme enda og må teste ut litt i staging.
- Fikser feil med recaptcha og feil bruk av custom elements som krasjet siden ved utlogging og noen ganger i overgang mellom telefon -> confirm code.

Teknisk:

- Legger til babel for å kunne transpilere kode i index.js for enklere feilhåndtering (try/catch med async code -> finally osv).
- Formatterer JSON og JS ihht. Prettier config.
- 

<img width="544" alt="Screenshot 2021-04-28 at 10 26 54" src="https://user-images.githubusercontent.com/606374/116371972-44117200-a80c-11eb-9173-52cb06f3938a.png">
<img width="1009" alt="Screenshot 2021-04-28 at 10 27 16" src="https://user-images.githubusercontent.com/606374/116372035-512e6100-a80c-11eb-8ddf-f1804b0e634a.png">

2021-04-28 13:49 UTC, magnusolderoesaether commented
Illustrasjon vises ikke i Safari

2021-04-28 13:56 UTC, mikaelbr commented
@magnusolderoesaether Joda! Fungerer i Safari, men for deploy på URL så ble ikke bilder inkludert. Fikser nå

2021-04-28 14:04 UTC, mikaelbr commented
Det er en visuell bug i Safari som gjør at hover på element som er i en container med overflow hidden og border radius ikke gjelder. Konsekvensene er at ved hover så vil knapp få ikke-radius. Kan fikses med litt CSS triksing, men som en egen oppgave.

2021-04-29 07:49 UTC, mikaelbr commented
Er en liten feil hvor det kan ligge igjen localstorage info uten at bruker er logget inn. Det fører til at man aldri får logget inn med mindre man fjerner localstorage. har en liten fiks som fordrer refresh nå men jobber kjapt med en fiks som åpner innlogginsskjema igjen med en feilmelding.

2021-04-29 08:45 UTC, mjenssen requested changes

2021-04-29 08:47 UTC, mikaelbr commented on src/static/index.js
> +            console.log('inside fetch auth info');
Ble fjernet som en del av a544488 og brukt i debugging 👍

2021-04-29 08:48 UTC, mikaelbr commented on src/static/index.js
> +            unsubscribeFetchUserDataSnapshot = db
Det blir gjort på linje 199 i toppen av funksjonen. Tanken er at uansett om det er en del av onboarding eller ikke så vil man unsubscribe på tidligere snapshot listeners.

2021-04-29 08:49 UTC, mikaelbr commented
La til endring med visning av auth error på toppnivå i a544488. Denne blir vist dersom du blir logget ut eller det skjer noe annet med innlogging.

2021-04-29 09:03 UTC, merged